### ISSUE TITLE
Question about D-Normal regulartization

### ISSUE THREAD

**Issue by BooguTeam** [HLinChen/VCR-GauS#4]
Hi, thanks for your great work. I am a little confused about the confidence map stated in **Confidence part** of paper "Learned from the **multi-view** pseudo normals". It seems the confidence term _w_ is calculated using the **single** view. Please correct me if I am wrong.

Besides, according to the eqn.12 & 13 in paper, the confidence term _w_ is calculated use the N^{-}_d, refered as the normal computed from the rendered depth (same in the eqn. 13). But in the code, the weight is calculated using [render_normal](https://github.com/HLinChen/VCR-GauS/blob/main/trainer.py). Should it be [est_normal](https://github.com/HLinChen/VCR-GauS/blob/main/gaussian_renderer/__init__.py#L22)? Please correct me if I am wrong.

Thanks again for your great work~

**Comment by HLinChen** [comment]
1. As we said in the introduction of our paper, 'Typically, the predicted normal maps from different views are combined to assess the uncertainty of a specific view. However, it is challenging to find correspondence across different views. We circumvent this issue by using the rendered normal learned from multi-view normal priors since we notice that it represents an average of normal priors across views.' It means the rendered normal of the single view learned from multi-view normal priors can represent the average of normal priors across views.

2. This is a typo. Thanks for pointing it out. We will update it in the final version. We will add some math proof and illumination about normal vs. d-normal in the final version.

**Comment by Harr7y** [comment]
Thanks for your reply. So the **multi-view normal prior** is contained in the pre-trained monocular normal estimator?

**Comment by HLinChen** [comment]
The rendered normal contains the multi-view normal priors from the pre-trained normal estimator.

**Comment by Harr7y** [comment]
Thanks for your reply. Have a nice day.
